services:
  - type: web
    name: attendance-app
    env: python
    buildCommand: "echo 'from django.contrib.auth import get_user_model; get_user_model().objects.create_superuser(\"Akira\", \"zerokaido15@gmail.com\", \"MyPassword\")' | python manage.py shell"

    startCommand: "gunicorn attendance_system.wsgi:application"
    envVars:
      - key: SECRET_KEY
        fromEnvVar: SECRET_KEY
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: attendance-app.onrender.com
      - key: DATABASE_URL
        fromEnvVar: DATABASE_URL
