# Generated by Django 5.2 on 2025-04-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='location',
        ),
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.TextField(default='No Description Provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='venue',
            field=models.CharField(default='No Venue Provided', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
