# Generated by Django 5.2 on 2025-05-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
