# Generated by Django 5.2 on 2025-05-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_delete_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
    ]
