# Generated by Django 5.2 on 2025-05-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_meeting_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='agenda',
            field=models.CharField(max_length=255),
        ),
    ]
